# Generated by Django 2.1 on 2022-06-28 01:01

from django.db import migrations, models
import django.db.models.deletion

"""here we can see the migration python file,which includes all the operation for bringing our database up to date with our current model classes
all this is done automatically by django"""

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                #this includes all the fields that we created in our model classes + the 'id' field automatically added by django

                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('number_in_stock', models.IntegerField()),
                ('daily_rate', models.FloatField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
    ]
"""we will need to run this file for or migration to be applied, to do to we need to run the command, "python manage.py manage" in the terminal, 
all of our data will than be showed in the sqlite3 database, along with a lot of data such as the date-time the migration was applied and the name of said migration"""

"""to obtain the exact SQL statements used by django in our migrations we need to open the terminal and use "python manage.py sqlmigrate .....(specify the app you want to look at ) ......(the number in front of the migration name)"
for example: say we want to know the sql command used in the migration file we are in now we would run python manage.py sqlmigrate movies 0001 this will display all the SQL statements that is sent to the database.

go to the admin module under the movies directory for continued notes...>
 """
